// Code generated by go generate DO NOT EDIT.

package main

import "github.com/samber/lo"


// Filter
func (xs Users) Filter(predicate func(item *User, index int) bool) Users {
	return lo.Filter(xs, predicate)
}

// Map
func (xs Users) Map(iteratee func(item *User, index int) *User) Users {
	return lo.Map(xs, iteratee)
}

// FilterByUserID
func (xs Users) FilterByUserID(UserID string) Users {
	return lo.Filter(xs, func(item *User, index int) bool {
		return item.UserID == UserID
	})
}

// KeyByUserID
func (xs Users) KeyByUserID() map[string]*User {
	return lo.KeyBy(xs, func(item *User) string {
		return item.UserID
	})
}
