// Code generated by go generate DO NOT EDIT.

package main

import "github.com/samber/lo"


// Filter
func (xs UserList) Filter(predicate func(item User, index int) bool) UserList {
	return lo.Filter(xs, predicate)
}

// Map
func (xs UserList) Map(iteratee func(item User, index int) User) UserList {
	return lo.Map(xs, iteratee)
}

// FilterByUserID
func (xs UserList) FilterByUserID(field string) UserList {
	return lo.Filter(xs, func(entity User, index int) bool {
		return entity.UserID == field
	})
}

// FilterByInt
func (xs UserList) FilterByInt(field int) UserList {
	return lo.Filter(xs, func(entity User, index int) bool {
		return entity.Int == field
	})
}

// FilterByIntPtr
func (xs UserList) FilterByIntPtr(field *int) UserList {
	return lo.Filter(xs, func(entity User, index int) bool {
		return entity.IntPtr == field
	})
}

// FilterByBool
func (xs UserList) FilterByBool(field bool) UserList {
	return lo.Filter(xs, func(entity User, index int) bool {
		return entity.Bool == field
	})
}

// FilterByBoolPtr
func (xs UserList) FilterByBoolPtr(field *bool) UserList {
	return lo.Filter(xs, func(entity User, index int) bool {
		return entity.BoolPtr == field
	})
}

// FilterByStr
func (xs UserList) FilterByStr(field string) UserList {
	return lo.Filter(xs, func(entity User, index int) bool {
		return entity.Str == field
	})
}

// FilterByStrPtr
func (xs UserList) FilterByStrPtr(field *string) UserList {
	return lo.Filter(xs, func(entity User, index int) bool {
		return entity.StrPtr == field
	})
}

// FilterByStruct0
func (xs UserList) FilterByStruct0(field DefinedStruct0) UserList {
	return lo.Filter(xs, func(entity User, index int) bool {
		return entity.Struct0 == field
	})
}

// FilterByStructPtr0
func (xs UserList) FilterByStructPtr0(field *DefinedStruct0) UserList {
	return lo.Filter(xs, func(entity User, index int) bool {
		return entity.StructPtr0 == field
	})
}

// FilterByStruct1
func (xs UserList) FilterByStruct1(field DefinedStruct1) UserList {
	return lo.Filter(xs, func(entity User, index int) bool {
		return entity.Struct1 == field
	})
}

// FilterByStructPtr1
func (xs UserList) FilterByStructPtr1(field *DefinedStruct1) UserList {
	return lo.Filter(xs, func(entity User, index int) bool {
		return entity.StructPtr1 == field
	})
}

// FilterByChanSend0
func (xs UserList) FilterByChanSend0(field chan<- int) UserList {
	return lo.Filter(xs, func(entity User, index int) bool {
		return entity.ChanSend0 == field
	})
}

// FilterByChanSendPtr0
func (xs UserList) FilterByChanSendPtr0(field *chan<- int) UserList {
	return lo.Filter(xs, func(entity User, index int) bool {
		return entity.ChanSendPtr0 == field
	})
}

// KeyByUserID
func (xs UserList) KeyByUserID() map[string]User {
	return lo.KeyBy(xs, func(entity User) string {
		return entity.UserID
	})
}

// KeyByInt
func (xs UserList) KeyByInt() map[int]User {
	return lo.KeyBy(xs, func(entity User) int {
		return entity.Int
	})
}

// KeyByIntPtr
func (xs UserList) KeyByIntPtr() map[*int]User {
	return lo.KeyBy(xs, func(entity User) *int {
		return entity.IntPtr
	})
}

// KeyByBool
func (xs UserList) KeyByBool() map[bool]User {
	return lo.KeyBy(xs, func(entity User) bool {
		return entity.Bool
	})
}

// KeyByBoolPtr
func (xs UserList) KeyByBoolPtr() map[*bool]User {
	return lo.KeyBy(xs, func(entity User) *bool {
		return entity.BoolPtr
	})
}

// KeyByStr
func (xs UserList) KeyByStr() map[string]User {
	return lo.KeyBy(xs, func(entity User) string {
		return entity.Str
	})
}

// KeyByStrPtr
func (xs UserList) KeyByStrPtr() map[*string]User {
	return lo.KeyBy(xs, func(entity User) *string {
		return entity.StrPtr
	})
}

// KeyByStruct0
func (xs UserList) KeyByStruct0() map[DefinedStruct0]User {
	return lo.KeyBy(xs, func(entity User) DefinedStruct0 {
		return entity.Struct0
	})
}

// KeyByStructPtr0
func (xs UserList) KeyByStructPtr0() map[*DefinedStruct0]User {
	return lo.KeyBy(xs, func(entity User) *DefinedStruct0 {
		return entity.StructPtr0
	})
}

// KeyByStruct1
func (xs UserList) KeyByStruct1() map[DefinedStruct1]User {
	return lo.KeyBy(xs, func(entity User) DefinedStruct1 {
		return entity.Struct1
	})
}

// KeyByStructPtr1
func (xs UserList) KeyByStructPtr1() map[*DefinedStruct1]User {
	return lo.KeyBy(xs, func(entity User) *DefinedStruct1 {
		return entity.StructPtr1
	})
}

// KeyByChanSend0
func (xs UserList) KeyByChanSend0() map[chan<- int]User {
	return lo.KeyBy(xs, func(entity User) chan<- int {
		return entity.ChanSend0
	})
}

// KeyByChanSendPtr0
func (xs UserList) KeyByChanSendPtr0() map[*chan<- int]User {
	return lo.KeyBy(xs, func(entity User) *chan<- int {
		return entity.ChanSendPtr0
	})
}
