// Code generated by go generate DO NOT EDIT.

package main

import "github.com/samber/lo"


// Filter
func (xs Users) Filter(predicate func(item *User, index int) bool) Users {
	return lo.Filter(xs, predicate)
}

// Map
func (xs Users) Map(iteratee func(item *User, index int) *User) Users {
	return lo.Map(xs, iteratee)
}
